In [1]:
import warnings
warnings.filterwarnings('ignore')
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix

In [2]:
pred=pd.read_excel('Predict.xlsx')

In [3]:
pred.head()

Gender  Fresher/Experience  10th Year of Pass out  10th Aggregate  \
0       2                   3                      0             0.0   
1       2                   3                      0             0.0   
2       1                   2                   2009            50.0   
3       1                   2                   2006            72.0   
4       2                   3                      0             0.0   

   12th Board  12th Course Type  12th/Diploma/ITI Year of Pass out  \
0           2                 1                                  0   
1           2                 1                                  0   
2           0                 1                               2013   
3           1                 0                               2008   
4           2                 1                                  0   

   12th/Diploma/ITI-Aggregate  Diploma Course Type  Diploma Stream  ...  \
0                        0.00                    1              12  ...   
1                        0.00                    1              12  ...   
2                       76.77                    2               1  ...   
3                       46.00                    1              12  ...   
4                        0.00                    1              12  ...   

   Currently Are You Working  State  Course(s)  Mode of Enquiry  Balance Fees  \
0                          0     18        358               12             0   
1                          0     18        358               12             0   
2                          0     12         27                6         23950   
3                          0     12         27                9         23950   
4                          0     18        358                6             0   

   Target_fees   Post date  Paid_fees  Paid_per  Paid_per_cat  
0            0  01-01-2018          0      -1.0             0  
1            0  01-01-2018          0      -1.0             0  
2        23950  01-01-2018          0       0.0             1  
3        23950  01-01-2018          0       0.0             1  
4            0  02-01-2018          0      -1.0             0  

[5 rows x 39 columns]

In [4]:
x=pred.drop(['Paid_fees', 'Paid_per', 'Paid_per_cat','Balance Fees','Post date'],1)
y=pred['Paid_per_cat']
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=42)

In [5]:
gbc=GradientBoostingClassifier()
gbc.fit(x_train,y_train)

GradientBoostingClassifier(criterion='friedman_mse', init=None,
                           learning_rate=0.1, loss='deviance', max_depth=3,
                           max_features=None, max_leaf_nodes=None,
                           min_impurity_decrease=0.0, min_impurity_split=None,
                           min_samples_leaf=1, min_samples_split=2,
                           min_weight_fraction_leaf=0.0, n_estimators=100,
                           n_iter_no_change=None, presort='auto',
                           random_state=None, subsample=1.0, tol=0.0001,
                           validation_fraction=0.1, verbose=0,
                           warm_start=False)

In [6]:
gbc_pred=gbc.predict(x_train)
print(accuracy_score(y_train,gbc_pred))
print()
print(confusion_matrix(y_train,gbc_pred))
print()
print(classification_report(y_train,gbc_pred))

0.9571655208884188

[[2922    0    0    0    0]
 [   0  548    0    2   95]
 [   0    3   22    0   10]
 [   0   16    0   53   77]
 [   0   39    0    1 1885]]

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      2922
           1       0.90      0.85      0.88       645
           2       1.00      0.63      0.77        35
           3       0.95      0.36      0.52       146
           4       0.91      0.98      0.94      1925

    accuracy                           0.96      5673
   macro avg       0.95      0.76      0.82      5673
weighted avg       0.96      0.96      0.95      5673



In [7]:
x_test.to_excel('Test.xlsx',index=False)

In [8]:
import pickle
from sklearn.externals import joblib
filename='Payment_pred.pkl'
joblib.dump(gbc,filename)

C:\Users\Rakshith KS\Anaconda3\lib\site-packages\sklearn\externals\joblib\__init__.py:15: DeprecationWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
  warnings.warn(msg, category=DeprecationWarning)


['Payment_pred.pkl']